

SCREEN_WIDTH, SCREEN_HEIGHT = 728, 508
BUFFER = 50
DISPLAY_WIDTH, DISPLAY_HEIGHT = SCREEN_WIDTH - 2 * BUFFER, SCREEN_HEIGHT - 2 * BUFFER
FOREGROUND_COLOR = (15, 15, 15)
BACKGROUND_COLOR = (0, 0, 0)
